### ISSUE TITLE
Quicklook url??

### ISSUE THREAD

**Issue by jeeftor** [deanishe/alfred-workflow#100]
Where is the `quicklookurl` option in Add_Item?  Am i missing it?

https://www.alfredapp.com/help/workflows/inputs/script-filter/json/

**quicklookurl : STRING (optional)**

A Quick Look URL which will be visible if the user uses the Quick Look feature within Alfred (tapping shift, or cmd+y)
`"quicklookurl": "https://www.alfredapp.com/"`

**Comment by deanishe** [comment]
Haven't added it yet.

To be honest, I read about it on the forum and I remembered that there was something missing from the JSON, but I couldn't remember what…

FWIW, `arg` is used if `quicklookurl` isn't specified.

**Comment by deanishe** [comment]
Added in [v1.21](https://github.com/deanishe/alfred-workflow/releases/tag/v1.21).
