### ISSUE TITLE
Cache confusion or issues

### ISSUE THREAD

**Issue by jeeftor** [deanishe/alfred-workflow#101]
So I'm having an issue where it looks like there is a cache file on my disk but the cache isn't being pulled down correctly?

So i have this little test script here:

```python
from workflow import  Workflow3

def main(wf):

    ckeys = ['exchange.Today', 'exchange.Tomorrow', 'google.Today', 'google.Tomorrow']

    for key in ckeys:
        print (key + " " + str(wf.cached_data(key)))

if __name__ == '__main__':
    wf = Workflow3(libraries=['./lib'],
                   )
    log = wf.logger

    wf.run(main)

```

In my cache directory i have a cache file for `exchange.Today` `exchange.Tomorrow`

<img width="769" alt="screen shot 2016-09-13 at 9 10 11 am" src="https://cloud.githubusercontent.com/assets/6491743/18474816/f0841b9a-7991-11e6-913b-98ec2bac1e16.png">

However the output of my script is:

```
exchange.Today [<lib.pyexchange.exchange2010.Exchange2010CalendarEvent object at 0x10cf92e90>, <lib.pyexchange.exchange2010.Exchange2010CalendarEvent object at 0x10db3c390>, <lib.pyexchange.exchange2010.Exchange2010CalendarEvent object at 0x10db3c5d0>]
exchange.Tomorrow None
google.Today None
google.Tomorrow None
```

I'm assuming there is some sort of cache timeout issue happening because if I run again later it will return 

```
exchange.Today None
exchange.Tomorrow None
google.Today None
google.Tomorrow None
```

Is this a bug or do I need a `max_age = 0` or something?>

(Now that I type this up i think probably i do need to pass a max_age) - and i just looked at the function signature and its true.

OOPS... Please close this bug.  Spent so much time typing it however I'll keep the post:)

**Comment by deanishe** [comment]
I messed up the caching API. `max_age` should definitely default to 0.
