### ISSUE TITLE
killing a background process

### ISSUE THREAD

**Issue by jeeftor** [deanishe/alfred-workflow#102]
Is there a way to kill a running background process from the workflow?  

Use case is for the AlfredToday workflow to do google OAuth it starts a local progress / web server on the system.  Sometimes it doesn't come up for random reasons and if you try again because the ports are locked it wont allow you to start a second one.  

So-> i'm currently doing 
```
    if is_running('auth'):
        log.info('!!WARNING!!! Background Authorization is already running!! - aborting')
    else:
        log.info('Launching bg task')

        run_in_background('auth',
                  ['/usr/bin/python',
                   wf.workflowfile('wf_authorize_google.py')])
```

I would like to be able to do an:

```
    if is_running('auth'):
       kill('auth')
```

 👍🏻️

**Comment by deanishe** [comment]
There isn't actually a `kill()` function, but I consciously wrote `background.py` in a way to make adding one fairly straightforward if anyone ever asked for it.

I haven't tested this code, but it's close to something that would work:

```python
import os
from signal import SIGTERM, SIGKILL

from workflow.background import is_running, _pid_file

def kill(job_name, force=False):
    """Kill a job started by `background.run_in_background()`."""
    if is_running(job_name):
        # Read PID from file created by `run_in_background()`
        pid = int(open(_pid_file(job_name)).read().strip())
        # Default to asking nicely
        sig = SIGTERM
        if force:  # Die, die, die!
            sig = SIGKILL
        
        os.kill(pid, sig)
        # Not strictly necessary to remove the now stale PID file,
        # as `is_running()` will do it on the next call
```
