### ISSUE TITLE
showing cover photos from the Internet

### ISSUE THREAD

**Issue by ttuygun** [deanishe/alfred-workflow#106]
I need to download every query to show cover photos from the Internet when I using wf.add_item(..., icon="http://..") but alfred-workflow don't support the images via downloaded the Internet. I can download images from Internet and placing a temp folder and showing them as wf.add_item(..., icon="temp/....png") but it's a bit longer process. Is there any method for this consequences?

Thanks in advance.

**Comment by deanishe** [comment]
Alfred doesn't (yet) support specifying icons by URL.

In this situation, I'd add the URLs to a queue and create a separate script that downloads the images in the background. Show a placeholder image in Alfred's results for images that haven't been downloaded yet. That way, you can still show results immediately in Alfred without waiting for the images to download.

You could also call Alfred via AppleScript to refresh the results after the images have been cached locally.

[Here](https://gogs.deanishe.net/deanishe/alfred-unwatched-videos/src/master/src/thumbnails.py)'s a similar script I wrote for generating thumbnails (the original images—movie/TV show covers—are too big to send dozens of them to Alfred). It depends on GraphicsMagick, installed via Homebrew.

**Comment by pat-s** [comment]
For everyone arriving here, here is what I did to get it working:

- add a [`thumbnail.py`](https://github.com/analogue-app/alfred-analogue/blob/master/thumbnails.py) to your workflow folder
- in your main script where you call `wf.add_item(icon = )` make sure that a URL is passed
- add [`util.py`](https://github.com/analogue-app/alfred-analogue/blob/master/workflow/util.py) to the `workflow` folder in your respective Alfred workflow folder 
- Add the following right after the `wf.add_item(icon = )` block as shown [here](https://github.com/analogue-app/alfred-analogue/blob/67c1dacb0a72b0a60dbbce97309664684ca80771/search.py#L47-L51)

  ```py
    thumbs.save_queue()
    if thumbs.has_queue:
        thumbs.process_queue()
        # TODO run in background
        if not is_running('generate_thumbnails'):
            run_in_background('generate_thumbnails',
                              ['/usr/bin/python',
                               wf.workflowfile('thumbnails.py')])

    return 0
  ```
- Add `thumbs = Thumbs(wf.datafile("thumbs"))` just right before the `wf.add_item(icon = )` block as shown [here](https://github.com/analogue-app/alfred-analogue/blob/67c1dacb0a72b0a60dbbce97309664684ca80771/search.py#L33)
- Add `from thumbnails import Thumbs` to your respective python file containing `wf.add_item(icon = )`
- Add `from workflow import util` to your respective python file containing `wf.add_item(icon = )`
