### ISSUE TITLE
Is it possiable to add a click listener to a notification?

### ISSUE THREAD

**Issue by ghuiii** [deanishe/alfred-workflow#108]
I saw below code in [your site](http://www.deanishe.net/alfred-workflow/user-manual/notifications.html#notifications), and there I can't found a way to set a click listener to the notification, something like open a http url. 
If it doesn't support yet for now, Can you please to add the feature.
```python
from workflow.notify import notify

notify('My Title', 'My Text')
```

**Comment by deanishe** [comment]
It's not supported, and I almost certainly won't add the feature.

It's not as simple as saying "and here's a URL" to the system, and AppleScript (which Notify.app is written in) has a pretty limited notifications API.

**Comment by ghuiii** [comment]
But I had seen a lot of apps can do that. So I guess there may be some api can do that.

**Comment by deanishe** [comment]
Alfred-Workflow isn't an app.

**Comment by ghuiii** [comment]
@deanishe  That it to say the "alfred" app doesn't provide the api to do this.
