### ISSUE TITLE
Change `cache_serializer` won't change the background worker's `cache_serializer`.

### ISSUE THREAD

**Issue by dozer47528** [deanishe/alfred-workflow#113]
I changed the `cache_serializer` to `json`. When I try to call `update_available`, the code will use the `json` to read the `__workflow_update_status`.

But I find that the background update checker will still use the `cpickle`.

So the auto-update doesn't work.

**Comment by deanishe** [comment]
Fixed in [v1.25.1](https://github.com/deanishe/alfred-workflow/releases/tag/v1.25.1). It's also on the Cheeseshop.

**Comment by dozer47528** [comment]
@deanishe Thanks for update.
