### ISSUE TITLE
Downloading Workflow from Github does not work if extension is .alfred3workflow

### ISSUE THREAD

**Issue by skleinei** [deanishe/alfred-workflow#115]
Hey @deanishe, first of all thanks for this great lib. It helped me building a Confluence workflow to find and open Confluence pages ([more info](https://github.com/skleinei/alfred-confluence)).

Ok, enough said – here is the issue: 
The self-update (and especially the download part) is not working if the extension .alfred3workflow. If I change the extension to .alfredworkflow it works fine.

Being a Python noob and not having troubles getting the build+test to work, I don't have time to add a PR, but the issue is in `workflow/update.py`, lines ~206/207. If changed to this, it should work:
```
    :
    if (not (url.endswith('.alfredworkflow') or url.endswith('.alfred3workflow')) or
            not (filename.endswith('.alfredworkflow') or filename.endswith('.alfred3workflow'))):
    :
```
Hope this helps.

**Comment by deanishe** [comment]
This is the first time this issue has been reported, despite `.alfred3workflow` working for many people to date (including me).

Could you please first verify that the file in the release really has the extension `.alfred3workflow`?

If you try to change the `.alfredworkflow` extension to `.alfred3workflow` in Finder (without doing Get Info) or in the GitHub releases interface after you've uploaded an `.alfredworkflow` file, it doesn't work.

**Comment by deanishe** [comment]
My bad. Turns out it hasn't been working for anyone…

Issue is fixed in [v1.25.2](https://github.com/deanishe/alfred-workflow/releases/tag/v1.25.2)

**Comment by xilopaint** [comment]
Does it mean self-update is not working in 1.25.1? If so is it possible to easily tweak fixum to replace library versions prior to 1.25.2?

**Comment by deanishe** [comment]
> Does it mean self-update is not working in 1.25.1?

Yes. At least if you're using `.alfred3workflow` extensions to feed different versions to Alfred 3.

I've [updated Fixum](https://github.com/deanishe/alfred-fixum/releases/tag/v0.1.5) to update *all* older versions of AW.

**Comment by skleinei** [comment]
Thanks!
