### ISSUE TITLE
Unable to use zip'd version of alfred-workflow

### ISSUE THREAD

**Issue by eddyg** [deanishe/alfred-workflow#122]
I'm unable to leave the `alfred-workflow` module "zipped up", as described in the [docs](http://www.deanishe.net/alfred-workflow/installation.html#github).

Example:

```
localmac:~> python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, 'alfred-workflow-1.28.1.zip')
>>> import workflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "alfred-workflow-1.28.1.zip/workflow/__init__.py", line 64, in <module>
IOError: [Errno 20] Not a directory: 'alfred-workflow-1.28.1.zip/workflow/version'
```

The problem is line 64 in `init.py`:

```__version__ = open(os.path.join(os.path.dirname(__file__), 'version')).read()```

Is using a zipped version of the module no longer supported?

**Comment by deanishe** [comment]
I think at this point I'd have to say, yeah, it's no longer supported. Sorry.

I'll remove the relevant sections from the docs and README.

**Comment by deanishe** [comment]
Docs have been updated.
