### ISSUE TITLE
2429 WARNING  Can't save last version: workflow has no version

### ISSUE THREAD

**Issue by MrLevo520** [deanishe/alfred-workflow#123]
Hi~
    I meet some problems when i use workflow to build my own alfred. When i open the workflow directory in Terminal and run the script by hand to see the error: "2429 WARNING  Can't save last version: workflow has no version." But the xml work well, i can't figure it out.
Here is the whole thing when i execute my script:
`<?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>https://pan.baidu.com/s/1qY8xYVi</title><subtitle>zqtt</subtitle></item><item valid="no"><title>https://pan.baidu.com/s/1jIR7hye</title><subtitle>kr2v</subtitle></item><item valid="no"><title>http://pan.baidu.com/s/1i4RdFWp</title><subtitle>iua7</subtitle></item></items>15:17:22 workflow.py:2429 WARNING  Can't save last version: workflow has no version`
Result is FINE, only the last line get wrong and make alfred doesn't work~.Can you help me? Thanks~，fantastic project by the way!

**Comment by deanishe** [comment]
> only the last line get wrong and make alfred doesn't work

It shouldn't affect Alfred. The warning is written to STDERR/Alfred's debugger, while the XML goes to STDOUT/Alfred's input. If the workflow isn't working, it's almost certainly not because of the warning.

You can also ignore the warning if you're not trying to use the update or migration mechanism.

**Comment by MrLevo520** [comment]
Thanks a lot, but it just doesn’t wok in Alfred , when i use keyword to run my script ,it just skip my keyword and search for google and so on. Why this happend?

For example. My keyword is ‘gm’

[cid:C0E2AC43-1844-461E-8D11-B6A1FF67A665@lan]


When I use this ,it just search for google

[cid:54C09178-CA64-4C69-A5C4-735144EECFE9@lan]

在 2017年11月27日，下午7:07，Dean Jackson <notifications@github.com<mailto:notifications@github.com>> 写道：


only the last line get wrong and make alfred doesn't work

It shouldn't affect Alfred. The warning is written to STDERR/Alfred's debugger, while the XML goes to STDOUT/Alfred's input. If the workflow isn't working, it's almost certainly not because of the warning.

You can also ignore the warning if you're not trying to use the update or migration mechanism.

**Comment by deanishe** [comment]
> Why this happend?

I can't tell you that because I don't have the workflow.
