### ISSUE TITLE
Workflow Updating: Github no longer accepts `.alfredworkflow` files.

### ISSUE THREAD

**Issue by lukewaite** [deanishe/alfred-workflow#126]
It looks as though GitHub has locked down allowed file types when attaching a binary to a release.

![image](https://user-images.githubusercontent.com/618130/36739778-c8fb6f7c-1bae-11e8-893c-036f8da7b0bf.png)

> There must be one (and only one) .alfredworkflow and/or one (and only one) .alfred3workflow binary attached to a release otherwise the release will be ignored. This is the file that will be downloaded and installed via Alfred’s default installation mechanism.

Since we won't be able to attach `.alfredworkflow` files anymore, the updater will have to be updated - likely to look for a `zip`?

**Comment by deanishe** [comment]
It happens sometimes. Wait a few minutes and try the upload again.

**Comment by lukewaite** [comment]
Fantastic, it's working again.

Thanks!
