### ISSUE TITLE
Setting and resolving per-item variables

### ISSUE THREAD

**Issue by ericmartineau** [deanishe/alfred-workflow#128]
Great library, and I admit I'm a bit of a noob when it comes to python and Alfred...

Alfred supports the setting of variables on a per-item basis, and Alfred will use the item's value only if the item was selected.  I'm able to set the item variable like this:

```
item = wf.add_item(plugin, plugin_description)
item.setvar('gplugin_id', plugin_id)
```

I'm not finding any way to read that value back in.  After beating my head against the wall, I finally discovered that Alfred sends the value for these variables as environment variables only.  I assumed that I could do this in a subsequent action to retrieve the value:

```
wf.getvar('gplugin_id')
```

But that didn't work.  However, doing this does work:

```
os.getenv('gplugin_id')
```

I noticed that you've created a session scope, which is great for many use cases, but not this one because the selection of the item and capturing of the variable happens outside the scope of the python script (inside Alfred).

I could see a couple ways to approach this (maybe both would be beneficial):

1. The shortest and most failproof is to delegate to `os.getenv` in the case that `wf.variables` doesn't contain the desired key
2. If you want a more explicit/strict mode, you could use `os.getenv`to resolve all variables defined at the workflow level

Lastly, it would be nice to set variables inline for the `Item3` instance:

```
item = wf.add_item(plugin, plugin_description, variables={'gplugin_id', plugin_id})

# or even better, **kwargs
item = wf.add_item(plugin, plugin_description, gplugin_id=plugin_id)
```

**Comment by ericmartineau** [comment]
Sorry, forgot to mention that I'm happy to submit a PR, but wanted to see if there was something I was missing first, and which approach you'd prefer to take

**Comment by deanishe** [comment]
It works the way it does for a reason. Basically, [I don't want to blur the lines between workflow and environment variables](https://github.com/deanishe/alfred-workflow/issues/85#issuecomment-260509891).

**Comment by ericmartineau** [comment]
I opened a PR before I saw your comment - I have to go somewhere now but I'll respond a bit later.  You can ignore that PR

**Comment by ericmartineau** [comment]
Thx - that other thread filled in a lot of gaps for me.

It feels natural that a plugin developer will want to know "What's the current value of the workflow variable X?".  With the current implementation, it's not clear.

The environment is the only way to access upstream variable values currently, but you are correct that it introduces the possibility of false positives, specifically the case where I request a key that does not exist in my workflow state, but does exist in the environment.  It's probably worth calling out that this problem is completely avoidable simply by initializing the variables in the workflow variable configuration, or by good variable naming, so a flag (disabled by default) on `Workflow3` might be a decent middle ground. 

As for the PR, you make the call.  I'm happy to make any mods, or you can close it out.

**Comment by deanishe** [comment]
I appreciate where you're coming from. If the question keeps coming up, I'll change the behaviour.

> It's probably worth calling out that this problem is completely avoidable simply by initializing the variables

That's what I do. I tend to treat workflow variables like other environment variables. They normally get a section at the top of the script:

```python
VAR_ONE = os.getenv('VAR_ONE') or VAR_ONE_DEFAULT

**Comment by ericmartineau** [comment]
I still believe that `os.environ` is an implementation detail that workflow authors should not interact with explicitly.  We just want to get and set workflow variables, including upstream variables.

> It's probably worth calling out that this problem is completely avoidable simply by initializing the variables
I was referring to the "Configure Workflow and Variables" section in the UI.  If I create a variable named "USER", it will override the environment and will remain consistent with any uses of `{var:USER}`.  You could whitelist against this variable list to alleviate the risk of unintentionally resolving environment variables.

As for interprocess communication, you could require developers to manage it like you do now.

**Comment by deanishe** [comment]
> We just want to get and set workflow variables, including upstream variables.

Obviously. That doesn't address my reservations, however, and calling `os.getenv()` instead of `wf.getvar()` is hardly a significant inconvenience.
