### ISSUE TITLE
Question: Updating workflow and github

### ISSUE THREAD

**Issue by JiDai** [deanishe/alfred-workflow#139]
Hi,

I want to use `Workflow updates` feature but I have one question about repository organisation. I have all my workflow in one repo. Is it possible to use the feature by specifying a subfolder in workflow configuration ?

**Comment by deanishe** [comment]
No. The [docs are *very* clear that updates use GitHub releases](http://www.deanishe.net/alfred-workflow/guide/update.html#id2).

Try [OneUpdater](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) instead.

**Comment by JiDai** [comment]
ok, thanks
