### ISSUE TITLE
Cache Image

### ISSUE THREAD

**Issue by emsilva** [deanishe/alfred-workflow#142]
I tried to review your code on 
https://gogs.deanishe.net/deanishe/alfred-unwatched-videos/src/master/src/thumbnails.py but I couldn't make sense of it, I apologize. Can you please provide us with an example on how to use caches to trigger image downloads to be used as icons after a period? Thank you for the amazing work.

**Comment by deanishe** [comment]
Did you look at [search.py in the same workflow](https://git.deanishe.net/deanishe/alfred-unwatched-videos/src/branch/master/src/search.py)? That's where it's used.

**Comment by deanishe** [comment]
Did you figure this out?

**Comment by MikeMajara** [comment]
I have not been able to cache images and retrieve them. The code you point out to seems to cache images that are already written to disk and thumbnails are made from these. But, how would you cache a bytearray with the provided functions by Workflow3, and then pass it on to add_item with a normal path...? 

If that is even possible with the library as is. I mean.

**Comment by deanishe** [comment]
>  The code you point out to seems to cache images that are already written to disk and thumbnails are made from these.

Yes, but it's very straightforward to adapt it to fetch a URL instead. All you have to do is replace the call to `/usr/local/bin/gm` with one to `curl`.

> But, how would you cache a bytearray with the provided functions by Workflow3

You wouldn't. The built-in caching functions are for storing data structures, and the data are serialised to disk. All the on-disk files are in Python's pickle format.

> If that is even possible with the library as is. I mean.

It doesn't provide a method to write a bunch of bytes as-is to disk, no. Why would it? That's what `open` is for.

**Comment by MikeMajara** [comment]
Perfect! That got me on track. I thought I was missing something and that it might be possible to do with the pickling. Thanks a lot for the prompt response! 👍
