### ISSUE TITLE
Basic auth 

### ISSUE THREAD

**Issue by JiDai** [deanishe/alfred-workflow#143]
Hi,

I have an API with basic auth. I have a username as a token but I must leave the password blank. Here is how I call the API :

```
response = requests.get(API_URL, auth=HTTPBasicAuth(wf.info.variables.token, ''))
```

I tried to use the built web client : 

```
response = workflow.web.get(API_URL, auth=(wf.info.variables.token, ''))
```

The first solution works but not the second, I have a 401 code.
I supposed this is because I pass a blank password. When debugging requests sent to the server (with Charles), I don't see the right headers in request. 
Can you confirm the problem ?

**Comment by deanishe** [comment]
> Can you confirm the problem ?

No. `httpbin` (which the unittests use) doesn't support basic auth with no password. Perhaps you know an API I can test it against?

You could try [composing the `Authorization` header yourself](https://stackoverflow.com/a/2955687/18763).

**Comment by JiDai** [comment]
It is the [PackageCloud.io API](https://packagecloud.io/docs/api). I finally used `request` module.

**Comment by deanishe** [comment]
Glad you got it working.
