### ISSUE TITLE
set_config raises error when the bundle id is null

### ISSUE THREAD

**Issue by HaoboGu** [deanishe/alfred-workflow#146]
Alfred version: 3.8.2
alfred-workflow version: 1.37.1

When I run the following code snippet will raises error:
```python
def main(wf):
    log = wf.logger
    if len(wf.args):
        hugo_path = wf.args[0]
        if os.path.exists(hugo_path):
            set_config("HUGO_HOME", str(hugo_path), exportable=False)
            print("Successful!", end="")
        else:
            print("Please specify a valid path", end="")
    wf.send_feedback()
```

0:157: execution error: Error on line 1: Error: Can't convert types. (-1700)
16:29:26 workflow.py:2080 ERROR    Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', 'Application("Alfred 3").setConfiguration("HUGO_HOME", {"exportable": false, "inWorkflow": null, "toValue": "/Users/haobogu/Projects/resources/_gen/assets"});']' returned non-zero exit status 1

I think this is because the "inWorkflow" term is null. After I set a bundle id for my workflow, the code runs well. Is it a bug?

**Comment by deanishe** [comment]
> Is it a bug?

It's arguably a bug that the library doesn't immediately raise an exception if no bundle ID is set.

It's required by many library features, and it's impossible to call Alfred's configuration API without one because Alfred needs to know which workflow you're trying to modify.

You **must** set a bundle ID.

**Comment by HaoboGu** [comment]
If I set a bundle ID to my workflow, how do I ensure that the ID I set won't be conflict with workflows wrote by others?

**Comment by deanishe** [comment]
Use a reversed domain name that you own, like everybody else does.

**Comment by HaoboGu** [comment]
thanks!
