### ISSUE TITLE
Setting only arg on Variables adds line break

### ISSUE THREAD

**Issue by sniarn** [deanishe/alfred-workflow#147]
When setting Variables from a Run Script action that include both arg and variables, everything is fine. Like so:

```py
v = Variables(u'arg', var1='val1')
print(v)
```

However, if you only set an output arg — like below — an unwanted line break is appended to the output and subsequent trimming is required.

```py
v = Variables(u'arg')
print(v)
```

**Comment by deanishe** [comment]
Sorry, didn't look at this one properly. This isn't a bug in the library. `print` is adding the line break.

Use `sys.stdout.write(str(v))` or `print(v, end='')`.
