### ISSUE TITLE
cant get output

### ISSUE THREAD

**Issue by fulln** [deanishe/alfred-workflow#163]
Here is my code:
```python
#!/usr/bin/python
# encoding: utf-8

import sys

from workflow import Workflow3


def main(wf):
    args = wf.args

    wf.add_item(title=switch(args[0]),subtitle=args[0],arg=switch(args[0]))
    
    wf.send_feedback()


def switch(arg):
    list = ['changyong', 'gaoxing', 'maimeng', 'zhenjing', 'shengqi', 'wunai', 'yun', 'daoqian', 'dongwu', 'haixiu', 'ku', 'memeda', 'shuila', 'zaijian', 'aojiao', 'chihuo', 'deyi', 'haipa', 'jiong', 'zan', 'nanguo', 'jian', 'qita']
    if len(arg) >1 :
        for key in list:
            if key.find(arg) != -1:
                return key

if __name__ == '__main__':
    wf = Workflow3()
    sys.exit(wf.run(main))
```
i had add the 'copy to clipboard' after 'Script Filter'  but  it does not work

**Comment by fulln** [comment]
my Alfred version is 4.0.3

**Comment by deanishe** [comment]
What does Alfred's debugger say?

**Comment by fulln** [comment]
![image](https://user-images.githubusercontent.com/24662311/85018096-32e4e700-b19f-11ea-91e4-50658491df57.png)

it dose not print any error or tips ，it's a sample demo  but i cant get any response after enter...

**Comment by fulln** [comment]
> What does Alfred's debugger say?

finally i choose to use shell to realize my workflow rather than your project..Σ( ° △ °|||)︴ 
,but thanks for your replay (๑•̀ㅂ•́)و✧

**Comment by deanishe** [comment]
Right. It *is* working (i.e. it's showing results).

You can't "action" the item because you have `valid = False`. Use `wf.add_item(..., valid=True)`.

**Comment by whtis** [comment]
> Right. It _is_ working (i.e. it's showing results).
> 
> You can't "action" the item because you have `valid = False`. Use `wf.add_item(..., valid=True)`.

I also meet this problem. it can not work via set`valid=Ture`, i can't see the result in my clipboard  either...my version is 3.6.2

unlike other tool, my workflow can not give a response when i enter the "enter key".can you help me? thanks

**Comment by whtis** [comment]
![image](https://user-images.githubusercontent.com/15317565/85530732-bdff2a80-b640-11ea-9e83-31c8be2270cc.png)
```
# -*- coding:utf-8 -*-
import json, sys
from workflow import Workflow, web


def main(content):
    str = u'this is test sentence'
    wf.add_item(str, valid=True)
    wf.send_feedback()


if __name__ == '__main__':
    wf = Workflow()
    sys.exit(wf.run(main))
```

code like this @deanishe

**Comment by deanishe** [comment]
> code like this

You can't action that item: it doesn't have any value set. Alfred won't let you action an item with no `arg`.

**Comment by whtis** [comment]
> > code like this
> 
> You can't action that item: it doesn't have any value set. Alfred won't let you action an item with no `arg`.

this is my first time to write a wf, so i don't know how to fix it, actually my purpose is simple, by using your project to get some text and copy to the clipboard. I already add a "copy to clipboard" after script like this:
![image](https://user-images.githubusercontent.com/15317565/85542501-b98c3f00-b64b-11ea-9708-0b67fdcdb14b.png)

what shoud i do next?

**Comment by fulln** [comment]
> > > code like this
> > 
> > 
> > You can't action that item: it doesn't have any value set. Alfred won't let you action an item with no `arg`.
> 
> this is my first time to write a wf, so i don't know how to fix it, actually my purpose is simple, by using your project to get some text and copy to the clipboard. I already add a "copy to clipboard" after script like this:
> ![image](https://user-images.githubusercontent.com/15317565/85542501-b98c3f00-b64b-11ea-9708-0b67fdcdb14b.png)
> 
> what shoud i do next?

https://www.deanishe.net/alfred-workflow/

**Comment by whtis** [comment]
> > > > code like this
> > > 
> > > 
> > > You can't action that item: it doesn't have any value set. Alfred won't let you action an item with no `arg`.
> > 
> > 
> > this is my first time to write a wf, so i don't know how to fix it, actually my purpose is simple, by using your project to get some text and copy to the clipboard. I already add a "copy to clipboard" after script like this:
> > ![image](https://user-images.githubusercontent.com/15317565/85542501-b98c3f00-b64b-11ea-9708-0b67fdcdb14b.png)
> > what shoud i do next?
> 
> https://www.deanishe.net/alfred-workflow/

i know this, but i can not find the reason...

**Comment by whtis** [comment]
> > code like this
> 
> You can't action that item: it doesn't have any value set. Alfred won't let you action an item with no `arg`.

got it, thanks!
