### ISSUE TITLE
py2.6 support?

### ISSUE THREAD

**Issue by m1keil** [deanishe/alfred-workflow#61]
Hey guys,
What are your thoughts about supporting Python 2.6?
Alfred 2.0 supports OS X 10.6+ which comes by default with 2.6.

I see in PIP that the package is marked as py2.6 compatible, however unittests in travis are not configured to run with py2.6 and from quick check it looks broken (for example the `({}).format` doesn't work in 2.6, only `({0}).format`).

Thanks!

**Comment by deanishe** [comment]
I guess the Travis configuration is wrong. It is supposed to include 2.6.

It should be straightforward enough to ensure 2.6 support.

However, although AW doesn't absolutely depend on anything that wasn't in Python 2.6, it does depend on features that weren't present pre-10.8.

The main problem is #27. The `security` CLI program AW uses to store Keychain passwords doesn't work pre-10.8. It might be possible to work around this, but I don't have anything older than Yosemite to test it on. I'm fairly certain this is the only issue.

Is it worthwhile ensuring 2.6 support if AW isn't fully functional on 10.6/7?

**Comment by deanishe** [comment]
I've run the test suite with 2.6, and these are the bits that don't work in 2.6 so far:

- `background.py`
    - [ ] new style formatting
- `update.py`
    - [ ] `argparse` not available
- `test_web.py`
    - [ ] `assertIsNone` not available
    - [ ] new style formatting

**Comment by m1keil** [comment]
Well, unless you have usage statistics, it's tricky question to answer. 
If you look at [stats from Omni Software](http://update.omnigroup.com/), they have about 3% usage from OS X 10.7. So lets say Alfredapp have about the same distribution of users and 100000 active installations... So we are talking about 4k potential users. Out of these how many actually use custom workflows? Lets say 50% and out of these let's say 50% use AW workflows? So this affects about 1% percent? Is it important to you or not? :-) (obviously it's just a very rough guess which might be total BS)

If making the changes to fix the issues above is not too hard, I would vote yes. The only real bummer is the argparse part. My workflow actually brings argparse with it to try and support 2.6.

**Comment by deanishe** [comment]
I'm already going through the code. The changes are all pretty simple. The unit tests are by far the hardest part. `argparse` isn't a big deal, as the usage is totally trivial. It can easily be replaced with `optparse` or pure `sys.argv`.

As mentioned above, my main concern is that the Keychain access won't work pre-10.8, so some workflows will run on older installs and others won't.

At any rate, I've found [a library](https://bitbucket.org/kang/python-keyring-lib/src/8aadf61db38c70a5fe76fbe013df25fa62c03a8d/keyring/backends/OS_X.py?at=default) that can parse the output of `security find-generic-password -g …`, so it should be possible to get that working on older versions of OS X, too.

**Comment by deanishe** [comment]
Should all be fixed in 0551765 (v1.11.0).

**Comment by m1keil** [comment]
:+1: great!
