### ISSUE TITLE
filter: matching whole query without splitting to words

### ISSUE THREAD

**Issue by raine** [deanishe/alfred-workflow#65]
Hello.

I have a use case where I want to filter a collection based on input like `[a] -> a`, in such way that the results that exactly match the query get a higher score. I ran into a problem where for example a query `[a] -> a` would give a higher score to result like `a -> [a]` even if there was an exact match in that collection for that query.

So I dug a bit into how the filtering works and noticed that query is split into words and each of those words are matched against the items. That is why it sees results `[a] -> a` and `a -> [a]` as equal because the query is matched against them word by word, i.e. `["[a]", "->", "a"]`.  I came up with a workaround that did not involve changing alfred-workflow's source, and replaced all spaces with underscores in the query and the "comparison key". This prevents the word splitting from happening and exact matches work.

Anyway, do you think it might make sense to have an option in the `filter` function to skip the word splitting?

Hope this made sense.

**Comment by deanishe** [comment]
`Workflow.filter()` is meant to provide a bunch of "smart" comparisons that match the way people typically *abbreviate* names and an acceptable general *text* search, with a few knobs to twist.

The input you're testing is quite a long way from what `Workflow.filter()` is aimed at.

If I were you, I'd write a custom search/comparison function for that input.

**Comment by raine** [comment]
To be honest I don't think it's that unconventional use case. I'm also matching an alphanumeric string along with the type signature (`[a] -> a`) as a key.

The whitespace to underscore trick works perfectly so I'm happy with the current implementation.

https://github.com/raine/alfred-ramda-workflow

Thanks for the reply, deanishe.

**Comment by deanishe** [comment]
Sorry I didn't reply sooner. Got a bit too much on my plate atm.

If you don't want the word-splitting, don't use `Workflow.filter()`, but [`Workflow._filter_item()`](https://github.com/deanishe/alfred-workflow/blob/master/workflow/workflow.py#L1842) instead.

`Workflow.filter()` doesn't do much more than split the query into words, call `Workflow._filter_item()` on each word-item combination, and add up the scores. All the "real" work is in `Workflow._filter_item()`, which doesn't diddle with your query in any way.

That should be much closer to the behaviour you want.
