### ISSUE TITLE
store_data fails silently when called from a background thread

### ISSUE THREAD

**Issue by idpaterson** [deanishe/alfred-workflow#78]
My apologies, but I do not have time right now to investigate this further and thought I should reach out in case you have an idea what is going on here. I recently updated my production workflow to alfred-workflow 1.14 but did not realize that there was an issue with one of my stored_data items. A recent bug report brought this to light – one of my calls to stored_data works fine while the other fails silently. 

The one that fails is stored from a thread initiated by `futures.ThreadPoolExecutor`. I believe that this change is what caused the problem rather than anything changed in alfred-workflow. I do not see anything suspicious with the data and no changes have been made to the data since before the update.

So, do you happen to know whether store_data should be expected to work when called from a thread? It is called only once and nothing else is storing data concurrently.

**Comment by idpaterson** [comment]
Sorry for wasting your time here, it is very clear in the documentation that store_data does not work in a multithreaded environment, so I will just refactor this a bit.

**Comment by deanishe** [comment]
None of the code is thread safe. At least not on purpose. 

The assumption is you'll use `background.py` for parallel stuff. (Not that it's a direct replacement for threads as such).

I don't know what you're working on, so the idea might be no use, but I try to use cached data in the actual workflow and kick off updates in the background where possible.

**Comment by idpaterson** [comment]
Thanks for the insight. This bit of code was inside the sync which is already in the background with `background.py`. It is syncing to a local SQLite database, but the Wunderlist API requires a large number of requests in order to get all of the data so I had to parallelize some of those requests to get the initial sync process down from ~3 minutes to ~30 seconds. The API handles updates nicely so the amount of data fetched after the initial sync is minimal.

Anyway, I had always done the sync in the background and cached lists with `store_data` for use within the script filter. That was important for quick text parsing in the workflow since the command may reference a list name and it was slower to initiate a connection to SQLite just for that. Problem is that when I parallelized the various branches of the sync, I didn't move the `store_data` call back out to the main thread.

**Comment by deanishe** [comment]
I had a look at your workflow code. Looks good.

A few observations.

- Why is there an `__init__.py` file in the workflow root?
- You shouldn't need to add the parent directory to `sys.path` in `alfred-wunderlist-workflow.py`: the directory containing the main file is automatically added to `sys.path`.
- Don't bother with `locale.getlocale()` in `wunderlist.util`. There is no locale in workflows. Mac apps are launched via `launchd`, not your shell, so they inherit `launchd`'s almost empty environment. Locale is therefore the default C (i.e. ASCII). `/usr/bin/env python` will therefore always resolve to `/usr/bin/python` (i.e. the system Python) in a workflow. Dicking around with your own `launchd` environment to set the locale to something sane is a bad idea if you distribute your workflows, as it can hide errors that will occur on default configurations.

  The closest you can get on OS X (AFAIK) is [the `AppleLanguages` system setting](https://github.com/deanishe/alfred-searchio/blob/master/src/search.py#L97). The `AppleLocale` variable can have [values that Python chokes on](https://github.com/deanishe/alfred-relative-dates/issues/1).

**Comment by idpaterson** [comment]
Thanks, I'm not a python guru so the code is not great. Alfred-workflow was far superior to what I was using before so looked like the best choice for me (early versions of the workflow were done in applescript interacting directly with the Wunderlist desktop app).

A majority of my workflow's users are outside of the US, so awhile back it was determined that the locale-specific components like parsedatetime functioned better when attempting to use the user's locale. I do need to revisit this at some point, but it became necessary to set up the environment with the user's locale (in the shell script filter that calls the python script).
```bash
export LC_CTYPE="$(defaults read -g AppleLocale).UTF-8"
echo "{query}" > .query
/usr/bin/env python -O alfred-wunderlist-workflow.py "{query}"
```
