### ISSUE TITLE
Something is broken

### ISSUE THREAD

**Issue by fniephaus** [deanishe/alfred-workflow#80]
Hi @deanishe,

I've recently received quite a few bug reports from users that are unable to use my workflows, especially the ones with script filters.
Today, I decided to look through some of the code and hoped that I would find a problem.
Well, I guess I found it (I'm having the problem now, too), but I am unable to tell what it is.

Things I notices:
- There seems to be some sort of `.lock` file problem with alfred-workflow (#69), but that does not seem to cause my problem.
- When starting a script filter, I don't get any output, the debug log is empty in Alfred.
- Also, the processes do not seem to terminate (Activity Monitor is full of my Python processes)
- I was able to get it working by disabling everything that does something in background (Auto update, run_in_background, ...). Whenever I turn one of these features back on, the problem is coming back.
- Running my script manually in iTerm works as intended.

I will try to downgrade alfred-workflow to an older version, but I'm not sure if this is something that broke recently or even something that was broken by an AlfredApp update.

Any ideas?

**Comment by deanishe** [comment]
Python scripts just hanging in Alfred? It appears to be an issue with the Alfred–OS X–Python interaction.

I don't think it has anything to do with Alfred-Workflow, as I tried some non-AW Python scripts last time Python stopped working in Alfred for me, and they hung, too.

And, like for you, while everything still worked fine from the shell, Alfred would not run Python scripts. The only "fix" I've found so far is to reboot.

**Comment by deanishe** [comment]
Also, I'm pretty certain it's unrelated to #69, as I've also had the problem, and I never, ever use the "Terminate previous script" option.

**Comment by fniephaus** [comment]
Well, they seem to terminate if I don't use alfred-workflow's caching.
As soon as I re-enable update (which also uses caching), they hang again :cry:

**Comment by fniephaus** [comment]
Ok, so I'm still trying to find out what is causing this problem.
I believe it does have something to do with either the autoupdater and/or caching and/or settings...

**Comment by fniephaus** [comment]
```
    2713 ???  (in Python)  load address 0x10deed000 + 0x21efd  [0x10df0eefd]
      2713 fwrite  (in libsystem_c.dylib) + 153  [0x7fff89fd934a]
        2713 __sfvwrite  (in libsystem_c.dylib) + 194  [0x7fff89fd8dcb]
          2713 _swrite  (in libsystem_c.dylib) + 87  [0x7fff89fde202]
            2713 __write_nocancel  (in libsystem_kernel.dylib) + 10  [0x7fff9932b70e]
```
Looks like the processes spawned are trying to write something...

**Comment by deanishe** [comment]
Do you have the "Terminate previous script" option turned on or off?

**Comment by fniephaus** [comment]
It's turned off, do I need to turn it on?

**Comment by deanishe** [comment]
No. I would not recommend turning it on. That's just the most likely cause of erroneous lockfiles, imo.

I've no idea what the problem might be. This may be a completely different issue to the one I've seen.

**Comment by fniephaus** [comment]
It seems that `atomic_writer` is unable to write a file. I guess it's been used to make sure that there are no corrupt files written to disk, right?

**Comment by fniephaus** [comment]
There also seems to be something wrong with the autoupdater, or even `run_in_background()`, but I'm not sure what it is.
I just tried to debug it again and check for any `.pid` files. I really didn't do any writer operation and it all of the sudden worked again. Now I can't reproduce the problem :weary:

**Comment by fniephaus** [comment]
I just cleared the cache and now it's happening again...

**Comment by fniephaus** [comment]
Ok, I just spend 2 hours debugging the problem on my flight, and I seem to have found the problem:
https://github.com/deanishe/alfred-workflow/blob/e2462049e4ff5f0162f1727b24e02b09587c5892/workflow/workflow.py#L1492

If I comment the `console`-related lines out, everything seems to work again. Can you shed some light on why this is necessary?

**Comment by deanishe** [comment]
No idea, tbh. Background process trying to open/write to a closed file (STDERR)?

**Comment by deanishe** [comment]
Do you have code to reliably replicate the problem?

**Comment by fniephaus** [comment]
Looks like there's a problem writing to `stderr`, yes. I have attached a version of my `alfred-homebrew` workflow which always seems to have this problem: [Homebrew-for-Alfred.issue80.alfredworkflow.zip](https://github.com/deanishe/alfred-workflow/files/178839/Homebrew-for-Alfred.issue80.alfredworkflow.zip)

Let me know if you can replicate it.

**Comment by deanishe** [comment]
It happened again earlier, and I found out a bit more information about the problem until I had to reboot my computer to do some work.

I'm pretty sure it's *not* a regression in Alfred-Workflow. I had the issue with a workflow using v1.10, which is before any of the file locking.

From what I can tell, Alfred gets into a state where it blocks any workflow that writes more than about 500b to STDERR. It appears to then start and queue subsequent calls. As you kill the hung processes, Alfred starts new ones (which also hang). AW isn't starting the extra processes. I mean, it *is*, but because it's being run multiple times by Alfred when it shouldn't.

Once Alfred is in that state, it *appears* to block *any* script that writes more than about 500b to STDERR, i.e. not only AW-based ones.

I suspect AW workflows may be most affected because they are much more verbose in their logging.

Next time it locks up, I'll throw a load of stuff at STDERR with some bash and ruby to see what happens.

I will investigate further. I guess turning off logging to STDERR is the thing to do for the time being.

**Comment by deanishe** [comment]
[v1.17.2](https://github.com/deanishe/alfred-workflow/tree/v1.17.2) turns off STDERR logging. Can turn it back on if we can figure out the cause of the issue.

Now `Workflow.run()` just prints the version number, duration and path to the log file to STDERR.

**Comment by deanishe** [comment]
Looks like the underlying cause is a full buffer. From my tests, about 100kB written to STDERR is enough to lead to a hung process.

The next version of Alfred should fix the issue.

At that point, I'll back out the changes I made and turn STDERR logging back on.

**Comment by fniephaus** [comment]
Nice! Thanks for the info. Have you filed an Alfred bug or did you reach out to Andrew directly?

**Comment by deanishe** [comment]
The bug [was already on the forum](http://www.alfredforum.com/topic/8629-some-workflows-doesnt-extend/) after a fashion.

In fact, I should probably make a note in that thread.
