### ISSUE TITLE
get_password hangs

### ISSUE THREAD

**Issue by fniephaus** [deanishe/alfred-workflow#81]
I honestly don't know what it is lately, but there seems to be another issue. This time with `get_password` which hangs when trying to retrieve a password.
I tracked it down to [this line](https://github.com/deanishe/alfred-workflow/blob/7547c92a26e7e924011004d06ac07217b9d10483/workflow/workflow.py#L2925) and in particular to `p.wait()`. Can you make any sense out of this?

**Comment by fniephaus** [comment]
> Warning This will deadlock when using stdout=PIPE and/or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use communicate() to avoid that.

https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait

**Comment by fniephaus** [comment]
Closed in favor of #82

**Comment by deanishe** [comment]
I can't imagine `security` outputting enough to fill a buffer.

> Mac OS X, for example, uses a capacity of 16384 bytes by default, but can switch to 65336 byte capacities if large write are made to the pipe, or will switch to a capacity of a single system page if too much kernel memory is already being used by pipe buffers (see xnu/bsd/sys/pipe.h, and xnu/bsd/kern/sys_pipe.c; since these are from FreeBSD, the same behavior may happen there, too).

http://unix.stackexchange.com/a/11954

**Comment by fniephaus** [comment]
I can't imagine that as well, but for some reason `p.wait()` deadlocks. Using `communicate()` seems to work just fine.
