### ISSUE TITLE
cönfüsed.gif confuses git

### ISSUE THREAD

**Issue by fniephaus** [deanishe/alfred-workflow#83]
Not sure what is going on here, but it's a little annoying :smile: 
![image](https://cloud.githubusercontent.com/assets/2368856/14172453/662cc086-f738-11e5-9a79-f614706c387a.png)

**Comment by deanishe** [comment]
http://michael-kuehnel.de/git/2014/11/21/git-mac-osx-and-german-umlaute.html

Deutsche Sprache, schwere Sprache …

**Comment by fniephaus** [comment]
Really? :confused:
