### ISSUE TITLE
How best to support workflow variables?

### ISSUE THREAD

**Issue by deanishe** [deanishe/alfred-workflow#85]
So in Alfred 3 you can set variables from your Script Filter results by setting `arg` to a JSON-encoded `{"alfredworkflow":{"arg":...}}` dictionary.

I've been exploring this mechanism in a [Go library](https://gogs.deanishe.net/deanishe/awgo) (Go's a PITA for this, btw). How I currently have that one working is that you can set variables at the `Workflow`, `Item` or `Modifier` level. When you create a new `Item` or `Modifier`, it inherits its parent's variables _at the time of creation_. So you can do:

``` go
wf.SetVar("api_key", api_key) // Inherited by all child Items

it := wf.NewItem("Item Title")
it.Subtitle = "Open in New Window"
it.SetVar("uuid", uuid)  // Inherited by child Modifiers

// CMD
m := it.NewModifier("cmd")
m.Subtitle = "Open in New Tab"
m.SetVar("open_in_tab", "1")

// ALT
m = it.NewModifier("alt")
m.Subtitle = "Open in Private Window"
m.SetVar("open_in_private", "1")

it.SetVar("open_in_win", "1") // Only set on Item, not Modifiers
```

Is that a solid solution for Alfred-Workflow? Too complex? Should variables (and arg) be resolved at feedback-generation time instead (i.e. `vars = wf.vars.copy(); vars.update(item.vars); vars.update(mod.vars)`)?

Or is variable inheritance a fundamentally bad idea?

Could maybe even make different `Feedback` classes with different variable inheritance behaviour.

**Comment by deanishe** [comment]
Added support for [workflow variables](http://www.deanishe.net/alfred-workflow/user-manual/workflow-variables.html) in the new [Workflow3](http://www.deanishe.net/alfred-workflow/api/workflow3.html#module-workflow3) class.

The current implementation follows the above-described inherit-on-creation model.

I guess that's kinda probably it now for v1.

Please add feedback to this issue regarding the v2 model.

Also `config`. Currently, there's an undocumented `config` dict that you can use, but it has no API.

**Comment by ViViDboarder** [comment]
It looks like this doesn't inherit variables from the OS, right?

Is there a reason you chose not to implement `Workflow3.getvar` as

    def getvar(self, name, default=None):
        """Variable storage that falls back to environ"""
        return self.variables.get(
            name,
            os.environ.get(name, default)
        )

**Comment by deanishe** [comment]
> Is there a reason you chose not to implement Workflow3.getvar…

Yes. For that to be meaningful, it would be necessary to automatically import the contents of `os.environ` into workflow variables. If you *don't* want that behaviour, it would be very hard to undo.

The converse—importing environment variables into workflow variables is very easy to do.

**Comment by ViViDboarder** [comment]
Why would it be required to automatically import the contents of `os.environ` as opposed to having `getvar` fallback to `os.environ` as I have above? So that there is consistency with `self.variables`?

**Comment by deanishe** [comment]
Fundamentally, the `getvar()` methods (`Workflow3.getvar()`, `Item3.getvar()` and `Modifier.getvar()`), like their "sister" `setvar()` methods, are for workflow variables *on the corresponding object*. That is to say, variables to be *exported* to Alfred, not workflow variables in general.

It would be confusing (imo) and bad practice for `setvar()` and `getvar()` to operate on different datasets. `setvar()` doesn't touch `os.environ`, so `getvar()` shouldn't either.

The `getvar()` methods exist purely as convenience methods to wrap `obj.variables.get()`. If it turns out that a lot of people assume they do the same as, or fall back on, `os.getenv()`, I will remove them. They really only exist to provide symmetry with the useful `setvar()` methods.

**Comment by jeeftor** [comment]
So am i doing something wrong here? 

```
import sys

from workflow import Workflow3
from workflow.background import is_running, run_in_background

def main(wf):
	log.info("HI")

	
	if is_running('bg'):
		log.debug(wf)
		log.debug(wf.variables)
		count = wf.getvar('count', None)
		log.info(count)

		wf.add_item('Running in bg', "YEa! " + str(count))

		count += 1
		wf.setvar('count',count)
		
	else: 
		# First Time Run
		wf.setvar('count','1')
		run_in_background('bg', ['/usr/bin/python', wf.workflowfile('bg.py')])
		wf.add_item('Starting bg')

	wf.send_feedback()

if __name__ == '__main__':
	wf = Workflow3()
	log = wf.logger
	sys.exit(wf.run(main))
```

I was trying to have a scrip that runs a background process and prints out elapsed time.  The idea was to run a background process and `rerun` ever second passing a `count` of how many times i've run in the foreground.  In my example `count` keeps coming in as `None` yet it shows that the "output" of my script the first time i run is:

```[2016-11-13 13:48:31][input.scriptfilter] {"items": [{"valid": false, "subtitle": "", "title": "Starting bg"}], "variables": {"count": "1"}}```

so this implies i'm not parsing it correctly on the rerun?

**Comment by jeeftor** [comment]
btw it works fine when i use this command

```
count = int(os.environ['count'])
```

**Comment by deanishe** [comment]
I explained this in the comment above yours. A newly-created `Workflows3` object has no variables.

**Comment by jeeftor** [comment]
Can you update the documentation to reflect the comments above?  Thats where I got thrown off. :)

**Comment by deanishe** [comment]
Will do. I'll have to have a think about how best to handle workflow and environment variables.

The implementation changed in 6b1fc2c, as Alfred 3.2 added "real" top-level workflow variables Previously `Workflow3.setvar()` was just a convenience to set variables on all `Item3` objects. Now it really sets top-level workflow variables (not that there's a lot of difference in practice).

I suspect what @ViViDboarder suggested is how most people would expect and/or prefer it to work, but I'm leery of conflating the "real" environment (i.e. `os.environ`) and workflow variables too much because they're not the same. For example, `$HOME` isn't a workflow variable (i.e. you can't do `{var:HOME}` in an Args & Vars Utility).

If `Workflow3.getvar()` gets a value from `os.environ`, should it "import" the variable, so it *is* set for downstream workflow objects (e.g. `Workflow.getvar('HOME')` would automatically make `{var:HOME}` work downstream)? If not, a user might think they're using a workflow variable when it's actually from `os.environ` and won't be visible to downstream objects.

If `Workflow3.getvar()` reads from `os.environ`, should `Workflow3.setvar()` also write to `os.environ` (so the variables would also be set when you call `run_in_background()` or `subprocess.call()`, and not just for downstream objects)?

**Comment by deanishe** [comment]
Also added a `Variables` class for setting workflow variables from Run Script actions.

Closing this issue, as the current behaviour doesn't seem to be causing problems.
