### ISSUE TITLE
Tried following the instructions of setting up alfred-workflow inside a folder and got an error

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-workflow#86]
I created a directory where I want to create my workflow. I then did ```pip install --target=. Alfred-Workflow``` command which was stated in the README but I got an error like so : 

![2016-06-06 at 19 07](https://cloud.githubusercontent.com/assets/6391776/15830678/feb71c5a-2c19-11e6-89a8-2101161c5c50.png)

I am not really sure what the issue is.

**Comment by deanishe** [comment]
It's a pip bug. `--target` doesn't work with pip if you've installed it in a Homebrew Python.
