### ISSUE TITLE
automatic updating (SOLVED)

### ISSUE THREAD

**Issue by jceelen** [deanishe/alfred-workflow#87]
Hello, 

I'm quite new to programming, python, git and alfred workflows your library and clear documentation helps a lot! There is one thing I cannot figure out right now, automatic updates through git. This is my setup: https://github.com/jceelen/alfred-10000ft-scripts/tree/v0.3 I changed the version file on my local workflow to 0.2 to try to update. 
If I use the magic argument `workflow:update` I get an error saying there are no valid releases for `jceelen/alfred-10000ft-scripts`.

BTW: I also use your build and install scripts. Thanks for the great work on both!

**Comment by idpaterson** [comment]
It looks like you will just need to attach your .alfredworkflow binary to the release. Click Edit next to that release, then drag and drop the proper .alfredworkflow file in the binaries section at the bottom.

**Comment by jceelen** [comment]
Thanks! @idpaterson That solved it!
