### ISSUE TITLE
'sub-menu's' and modifier keys

### ISSUE THREAD

**Issue by jceelen** [deanishe/alfred-workflow#88]
hello, 

I am trying to create a workflow for a projectmanagement tool that gives me fast acces to specific project pages on the web. It currently lists all the projects and I have different keywords to start the workflow with different outcomes, `10kpe` opens the project in edit mode while `10kpv` opens the project in view mode. This is not very user-friendly and developer friendly :-).

Since I am not a very experienced developer I cannot figure out what the best way is to create a 'sub-menu' of actions/options after selecting something from the first list. A second option that would be nicer than the current solution could be using different actions with the modifier keys (alt for editing, ctrl for running a report etc.). I went through the documentation, forums etc, even tried reading through different scripts like searchio but it's a bit to complex for me know :-) where can I find a clear example?

**Comment by deanishe** [comment]
This is a question for the [Alfred Forums](http://www.alfredforum.com).
