### ISSUE TITLE
ImportError: No module named 'cPickle' ?

### ISSUE THREAD

**Issue by Critter** [deanishe/alfred-workflow#90]
Traceback (most recent call last):
      File "dash-workflow.py", line 5, in <module>
        from workflow import Workflow, ICON_WEB, httplib2
      File "/workflow/__init__.py", line 26, in <module>
        from .workflow import Workflow, manager
      File "/workflow/workflow.py", line 22, in <module>
        import cPickle
    ImportError: No module named 'cPickle'

is there something else that I need to install to use the workflow object?

**Comment by deanishe** [comment]
Which Python are you trying to use it with? How did you install it?

**Comment by Critter** [comment]
That error was after I tried using python3. I was able to get things working using python 2 ¯\\\_(ツ)_/¯

**Comment by deanishe** [comment]
By way of explanation, Python 3 is *not* supported.
