### ISSUE TITLE
Alfred 3 cache directory vs alfred 2

### ISSUE THREAD

**Issue by jeeftor** [deanishe/alfred-workflow#95]
Is there a way to specific the correct workflow data and cache directories for alfred 3?

**Comment by deanishe** [comment]
The correct directories are automatically used depending on which version of Alfred is running the workflow.

If you're not running the workflow from Alfred, then you should set the `alfred_workflow_data` and `alfred_workflow_cache` environment variables to the correct directories.

I will update the `Workflow3` class to default to Alfred 3's directories when the environment variables are not set.
