### ISSUE TITLE
Erase a settings value

### ISSUE THREAD

**Issue by jeeftor** [deanishe/alfred-workflow#96]
Pardon is this is a dumb question but what is the syntax to remove a settings entry from the settings.json file

`wf.settings[key] = None` ?

**Comment by idpaterson** [comment]
You're looking for the `del` keyword to remove a key from a dict. Alfred-Workflow handles that to make sure that settings.json is updated as it is when you make any other changes to the settings.

```
del wf.settings[key]
```
