### ISSUE TITLE
Feature Request:  Update plist to match VERSION file

### ISSUE THREAD

**Issue by jeeftor** [deanishe/alfred-workflow#98]
I was wondering if you'd be interested in having a command or something that would auto-update the version info in the plist file to match the VERSION file that you use for everything else in your script.  Might be worthwhile as its not hard to do with python and plist.  Just an idea.

**Comment by deanishe** [comment]
Actually, I'm planning to make the version file optional, with the version in info.plist being the definitive one.

I was waiting for Alfred to add the workflow version to the environment variables, which is now done.

**Comment by deanishe** [comment]
The version set in Alfred's Workflow Version field/`info.plist` now takes priority as of [v1.20](https://github.com/deanishe/alfred-workflow/tree/v1.20)
