### ISSUE TITLE
Python Code snippets missing from Tutorial Docs

### ISSUE THREAD

**Issue by rajeshksv** [deanishe/alfred-workflow#99]
Hey,

Python code snippets aren't appearing in https://github.com/deanishe/alfred-workflow/blob/master/docs/tutorial_1.rst . However in raw view(https://raw.githubusercontent.com/deanishe/alfred-workflow/master/docs/tutorial_1.rst), snippets are present. It may be due to some invalid tag or something. Please check.

Thanks!

**Comment by deanishe** [comment]
The problem is GitHub's ReST rendering. The documentation isn't meant to be read in the repo (I'm surprised it works as well as it does), but is rendered to HTML via Sphinx. Read it here:

http://www.deanishe.net/alfred-workflow/
